# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - MyBaaSApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub (if using DockerHub) or Azure Container Registry (ACR)
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }} # E.g., 'myregistry.azurecr.io'
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.REGISTRY_URL }}/mybaasapp:latest .

      - name: Push Docker image to registry
        run: |
          docker push ${{ secrets.REGISTRY_URL }}/mybaasapp:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App with Docker
        uses: azure/webapps-container-action@v1
        id: deploy-to-webapp
        with:
          app-name: 'MyBaaSApp'
          slot-name: 'Production'
          images: ${{ secrets.REGISTRY_URL }}/mybaasapp:latest
