name: Build and deploy Docker app to Docker Hub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to Docker Hub with username and password (without using GitHub Secrets)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: 'kampac'  # Replace with your Docker Hub username
          password: 'dckr_pat_kVCPVEU9c2QIdG19iok_0xZkIZw'  # Replace with your Docker Hub password or access token

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ~/.docker
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Build Docker image
        run: |
          docker build -t yourdockerusername/yourimage:${{ github.sha }} .
          docker tag yourdockerusername/yourimage:${{ github.sha }} yourdockerusername/yourimage:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push yourdockerusername/yourimage:${{ github.sha }}
          docker push yourdockerusername/yourimage:latest
