name: Build and deploy Docker app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to Docker Hub with username and password (without using GitHub Secrets)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: 'kampac'  # Replace with your Docker Hub username
          password: 'dckr_pat_kVCPVEU9c2QIdG19iok_0xZkIZw'  # Replace with your Docker Hub password or access token

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ~/.docker
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Build Docker image
        run: |
          docker build -t kampac/myapp:${{ github.sha }} .
          docker tag kampac/myapp:${{ github.sha }} kampac/myapp:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push kampac/myapp:${{ github.sha }}
          docker push kampac/myapp:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: 'Deploy Docker image to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'MyBaaSApp'  # Replace with your Azure Web App name
          slot-name: 'Production'  # Optionally use a slot name like 'Staging'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3643C36576C94933B74DC26D1125497B }}  # Ensure the correct publish profile secret is set
          images: 'kampac/myapp:${{ github.sha }}'  # Docker image name to deploy
