name: Build and deploy Docker app to Docker Hub and Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to Docker Hub with username and password (without using GitHub Secrets)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: 'kampac'  # Replace with your Docker Hub username
          password: 'dckr_pat_kVCPVEU9c2QIdG19iok_0xZkIZw'  # Replace with your Docker Hub password or access token

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ~/.docker
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Build Docker image
        run: |
          docker build -t kampac/yourimage:${{ github.sha }} .  # Replace 'yourimage' with your actual image name
          docker tag kampac/yourimage:${{ github.sha }} kampac/yourimage:latest  # Replace 'yourimage' with your actual image name

      - name: Push Docker image to Docker Hub
        run: |
          docker push kampac/yourimage:${{ github.sha }}  # Replace 'yourimage' with your actual image name
          docker push kampac/yourimage:latest  # Replace 'yourimage' with your actual image name

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: 'Deploy Docker image to Azure Web App'
        uses: azure/webapps-container-deploy@v1
        with:
          app-name: 'MyBaaSApp'  # Replace with your Azure Web App name
          slot-name: 'Production'  # Replace with your Azure Web App deployment slot if needed
          image: 'kampac/yourimage:${{ github.sha }}'  # Docker Hub image name and tag
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3643C36576C94933B74DC26D1125497B }}  # Replace with your Azure publish profile secret
